# Generated by Django 6.0.2 on 2026-02-13 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('general', 'Médecine Générale'), ('cardio', 'Cardiologie'), ('derma', 'Dermatologie'), ('pedia', 'Pédiatrie'), ('ortho', 'Orthopédie')], max_length=20)),
                ('room_number', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('priority', models.IntegerField(choices=[(1, 'Urgence'), (2, 'Prioritaire'), (3, 'Normal'), (4, 'Non urgent')], default=3)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('in_progress', 'En consultation'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='waiting', max_length=20)),
                ('ticket_number', models.CharField(max_length=10, unique=True)),
                ('estimated_wait_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='clinic.doctor')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='current_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='being_seen_by', to='clinic.patient'),
        ),
        migrations.CreateModel(
            name='QueueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clinic.patient')),
            ],
            options={
                'verbose_name_plural': 'Queue histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
