# Generated by Django 6.0.2 on 2026-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ticket_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
